### ISSUE TITLE
tested

### ISSUE THREAD

**Issue by smoochiee** [FTIndustries/chargemaster-500#1]
have you tested this?

**Comment by wb1016** [comment]
yes, it has been tested about a year ago. it should work flawlessly.

**Comment by smoochiee** [comment]
> yes, it has been tested about a year ago. it should work flawlessly.

if i want to add boost on this its posible to use 2 ouput?the 3.3v and 5v?

**Comment by wb1016** [comment]
you can just hook a boost convertor and an LDO.

**Comment by smoochiee** [comment]
> you can just hook a boost convertor and an LDO.

like this     ( output of tp4057 to ldo )
(output of tp4057 to boost?)

**Comment by wb1016** [comment]
to be more accurate, there's no output pin on TP4057. it is just a charger IC and it does not have protection feature.
you can just connect loads in parrallel with 4057.
